In [1]:
import numpy as np

In [2]:
ar1 = np.array([[1, 2, 3] , [4, 5, 6]])

In [3]:

ar1 = np.array([[1, 2, 3] , [4, 5, 6]])

In [4]:
ar1

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
ar1.sum(axis=0)

array([5, 7, 9])

In [6]:
ar2 = np.array([[2, 3, 4] , [4, 9, 11]])

In [7]:
ar2 = ar2.T

In [8]:
ar2.dot(ar1)

array([[18, 24, 30],
       [39, 51, 63],
       [48, 63, 78]])

In [9]:
ar2

array([[ 2,  4],
       [ 3,  9],
       [ 4, 11]])

In [10]:
ar2 = ar2.transpose()

In [11]:
ar2

array([[ 2,  3,  4],
       [ 4,  9, 11]])

In [12]:
ar2.dot(ar1.transpose())

array([[ 20,  47],
       [ 55, 127]])

In [13]:
ar2

array([[ 2,  3,  4],
       [ 4,  9, 11]])

In [14]:
ar1

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
ar2.dot(ar1.T)

array([[ 20,  47],
       [ 55, 127]])

In [16]:
ar2.T.dot(ar1)

array([[18, 24, 30],
       [39, 51, 63],
       [48, 63, 78]])

In [17]:
len(dir(np))

599

In [18]:
np.dot(ar2.T, ar1)

array([[18, 24, 30],
       [39, 51, 63],
       [48, 63, 78]])

In [19]:
a = ar1

In [20]:
b = ar2

In [21]:
np.cross(a, b)

array([[ -1,   2,  -1],
       [  1, -20,  16]])

In [22]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [23]:
b

array([[ 2,  3,  4],
       [ 4,  9, 11]])

In [24]:
np.sort(b)

array([[ 2,  3,  4],
       [ 4,  9, 11]])

In [25]:
np.sort(a, axis=0)

array([[1, 2, 3],
       [4, 5, 6]])

In [26]:
np.sort(b, axis=0)

array([[ 2,  3,  4],
       [ 4,  9, 11]])

In [27]:
b = np.array([[2, 5, 9] , [13, 9, 10]])

In [28]:
np.sort(b)

array([[ 2,  5,  9],
       [ 9, 10, 13]])

In [29]:
np.sort(b, axis=0)

array([[ 2,  5,  9],
       [13,  9, 10]])

In [30]:
b

array([[ 2,  5,  9],
       [13,  9, 10]])