In [1]:
import numpy as np
array1 = np.array([3, 2, 5, 7, 0])

In [2]:
print(array1)
print(type(array1))

[3 2 5 7 0]
<class 'numpy.ndarray'>


In [3]:
array1.shape

(5,)

In [4]:
np.zeros((4, 10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [5]:
def sahith() :
    print("Sahith")

In [7]:
sahith()

Sahith


In [8]:
"sahith"

'sahith'

In [9]:
con = [2, 2, 34, 234, 234, , 2343, 435]

SyntaxError: invalid syntax (4121177711.py, line 1)

In [10]:
con = [2, 2, 34, 234, 234, 23, 2343, 435]

TypeError: list indices must be integers or slices, not tuple

In [12]:
con.slice(3, 5)

AttributeError: 'list' object has no attribute 'slice'

In [13]:
con

[2, 2, 34, 234, 234, 23, 2343, 435]

In [14]:
arr

NameError: name 'arr' is not defined

In [15]:
array1

array([3, 2, 5, 7, 0])

In [16]:
array1[2, 3]

IndexError: too many indices for array: array is 1-dimensional, but 2 were indexed

In [17]:
array1 = [ 2, 3, 2,3 234, 234, 697, 234, 97]

SyntaxError: invalid syntax. Perhaps you forgot a comma? (1095023029.py, line 1)

In [18]:
array1 = 

In [19]:
array1 = np.array([ 23, 97, 978, 234, 97897, 23])
