In [1]:
import numpy as np

In [2]:
ar1 = np.array([[1, 2, 3] , [4, 5, 6]])

In [3]:
ar1 = np.array([[1, 2, 3 , 4] , 
                [4, 5, 6]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [4]:

ar1 = np.array([[1, 2, 3] , [4, 5, 6]])

In [5]:
ar1 = np.array([[1, 2, 3 , 10 , 10] , [4, 5, 6]])

ValueError: setting an array element with a sequence. The requested array has an inhomogeneous shape after 1 dimensions. The detected shape was (2,) + inhomogeneous part.

In [6]:
ar1

array([[1, 2, 3],
       [4, 5, 6]])

In [7]:
ar1.sum(axis=0)

array([5, 7, 9])

In [8]:
ar2 = np.array([[2, 3, 4] , [4, 9, 11]])

In [9]:
ar2 = ar2.T

In [10]:
ar2.dot(ar1)

array([[18, 24, 30],
       [39, 51, 63],
       [48, 63, 78]])

In [11]:
ar2

array([[ 2,  4],
       [ 3,  9],
       [ 4, 11]])

In [12]:
ar2 = ar2.transpose()

In [13]:
ar2

array([[ 2,  3,  4],
       [ 4,  9, 11]])

In [14]:
ar2.dot(ar1)

ValueError: shapes (2,3) and (2,3) not aligned: 3 (dim 1) != 2 (dim 0)

In [15]:
ar2.dot(ar1.transpose())

array([[ 20,  47],
       [ 55, 127]])

In [16]:
ar2

array([[ 2,  3,  4],
       [ 4,  9, 11]])

In [17]:
ar1

array([[1, 2, 3],
       [4, 5, 6]])

In [18]:
ar2.dot(ar1.T)

array([[ 20,  47],
       [ 55, 127]])

In [19]:
ar2.T.dot(ar1)

array([[18, 24, 30],
       [39, 51, 63],
       [48, 63, 78]])

In [20]:
len(dir(np))

599

In [21]:
np.dot(ar2.T, ar1)

array([[18, 24, 30],
       [39, 51, 63],
       [48, 63, 78]])

In [22]:
np.cross(ar1.T , ar2)

ValueError: shape mismatch: objects cannot be broadcast to a single shape.  Mismatch is between arg 0 with shape (3,) and arg 1 with shape (2,).

In [23]:
a = ar1

In [24]:
b = ar2

In [25]:
np.cross(a, b)

array([[ -1,   2,  -1],
       [  1, -20,  16]])

In [26]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [27]:
b

array([[ 2,  3,  4],
       [ 4,  9, 11]])