In [1]:
import numpy as np

In [2]:
myarr = np.array([[1, 2, 3, 4] ])

In [3]:
myarr

array([[1, 2, 3, 4]])

In [4]:
listarray = np.array([[1, 2, 3] , [5, 6 , 7] , [0, 1, 2]])

In [5]:
listarray

array([[1, 2, 3],
       [5, 6, 7],
       [0, 1, 2]])

In [6]:
listarray.size

9

In [7]:
zeros = np.zeros((2, 5))

In [8]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:

rng = np.arange(15)