In [11]:
import numpy as np
b = np.array([1, 3, 34, 10 , 23, 34, 71, 103, 98, 14, 34, 6980,    28, 97, 97, 29, 234, 9])

In [2]:
b.shape

(18,)

In [3]:
b = b.reshape(6, 3)

In [4]:
b

array([[   1,    3,   34],
       [  10,   23,   34],
       [  71,  103,   98],
       [  14,   34, 6980],
       [  28,   97,   97],
       [  29,  234,    9]])

In [5]:
b.sort()

In [6]:
b.sort

<function ndarray.sort>

In [7]:
b.sort()

In [8]:
b

array([[   1,    3,   34],
       [  10,   23,   34],
       [  71,   98,  103],
       [  14,   34, 6980],
       [  28,   97,   97],
       [   9,   29,  234]])

In [9]:
b.sort()

In [10]:
b.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [12]:
b = np.array([1, 3, 34, 10 , 23, 34, 71, 103, 98, 14, 34, 6980,    28, 97, 97, 29, 234, 9])

In [13]:
b.argsort()

array([ 0,  1, 17,  3,  9,  4, 12, 15,  5, 10,  2,  6, 13, 14,  8,  7, 16,
       11])

In [16]:
b.shape

(18,)

In [15]:
b.argsort()

array([ 0,  1, 17,  3,  9,  4, 12, 15,  5, 10,  2,  6, 13, 14,  8,  7, 16,
       11])

In [17]:
b

array([   1,    3,   34,   10,   23,   34,   71,  103,   98,   14,   34,
       6980,   28,   97,   97,   29,  234,    9])

In [19]:
b.argsort()

array([ 0,  1, 17,  3,  9,  4, 12, 15,  5, 10,  2,  6, 13, 14,  8,  7, 16,
       11])

In [20]:
b

array([   1,    3,   34,   10,   23,   34,   71,  103,   98,   14,   34,
       6980,   28,   97,   97,   29,  234,    9])

In [21]:
np.argmin()

TypeError: argmin() missing 1 required positional argument: 'a'

In [22]:
np.argmin(b)

0

In [ ]:
np.argmax()